apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springbootapp
  name: springbootapp
  namespace: springbootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapp-vj
  template:
    metadata:
      labels:
        app: springbootapp-vj
    spec:
      containers:
      - name: my-springbootapp-vj
        image: 490167669940.dkr.ecr.ap-southeast-1.amazonaws.com/eks-frontend-app-deployment:frontend-341
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootapp-vj
    k8s-app: springbootapp-vj
  name: springbootapp-vj
  namespace: springbootapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springbootapp-vj
